### ISSUE TITLE
Failed Build 32 Bit Ubuntu

### ISSUE THREAD

**Issue by KevinCooper** [blankwall/Python_Pin#1]
Downloaded the PIN tools from intel website and attempted to build with default 32 bit ubuntu image.  Get the following compilation error:

cc -DBIGARRAY_MULTIPLIER=1 -Wall -Werror -Wno-unknown-pragmas -fno-stack-protector -DTARGET_IA32 -DHOST_IA32 -DTARGET_LINUX  -I../../../source/include/pin -I../../../source/include/pin/gen -I../../../extras/components/include -I../../../extras/xed2-ia32/include -I../../../source/tools/InstLib -O3 -fomit-frame-pointer -fno-strict-aliasing   -c -o obj-ia32/INS.o INS.cpp -lpython2.7 -I/usr/include/python2.7 -rdynamic
In file included from /usr/include/signal.h:352:0,
                 from /usr/include/python2.7/pyfpe.h:129,
                 from /usr/include/python2.7/Python.h:156,
                 from INS.cpp:1:
INS.cpp: In function ‘PyObject\* Python_INS_InsertCall(PyObject_, PyObject_)’:
INS.cpp:105:29: error: reference to ‘REG_EAX’ is ambiguous
             IARG_REG_VALUE, REG_EAX,
                             ^
/usr/include/i386-linux-gnu/sys/ucontext.h:180:3: note: candidates are: <anonymous enum> REG_EAX
   REG_EAX,
   ^
../../../source/include/pin/gen/reg_ia32.PH:92:5: note:                 LEVEL_BASE::REG REG_EAX
     REG_EAX,
     ^
INS.cpp:106:29: error: reference to ‘REG_EBX’ is ambiguous
             IARG_REG_VALUE, REG_EBX,

.........
make: **\* [obj-ia32/INS.o] Error 1

Install on base 64 ubuntu image works fine.

**Comment by blankwall** [comment]
The 32 bit support is not functional atm. I will go ahead and work on it tonight expect this to be resolved soon.

**Comment by blankwall** [comment]
32 bit support is working!

**Comment by KevinCooper** [comment]
Thank you!

**Comment by cqy123456** [comment]
I meet the same question.
Can you tell me how to fix it ? @blankwall 
THANKS.
