### ISSUE TITLE
Issue executing examples/strace.py in Ubuntu 14.04 32-bit

### ISSUE THREAD

**Issue by insecuritea** [blankwall/Python_Pin#4]
When trying to execute examples/strace.py in Ubuntu 14.04 32-bit I get the following error:

symexec@ubuntu:~/pin/source/tools/Python_Pin$ ../../../pin -t obj-ia32/Python_Pin.so -m examples/strace.py -- /bin/ls
Traceback (most recent call last):
  File "examples/strace.py", line 4, in <module>
    unistd = open("/usr/include/x86_64-linux-gnu/asm/unistd_64.h").read().split("\n")
IOError: [Errno 2] No such file or directory: '/usr/include/x86_64-linux-gnu/asm/unistd_64.h'

Issue seems to be due to the hardcoded path to unistd_64.h
I got around this error by replacing the path to unistd to "/usr/include/i386-linux-gnu/asm/unistd_32.h"
Thanks.

**Comment by blankwall** [comment]
Updated the example to work for both 32 and 64 thanks for the heads up!
